#163388212 Users should be able to login
andela/ah-bird-box-frontend pull request #10
Opened 2019-03-13 09:52 UTC by bryan-munene

#### What does this PR do?

This PR sets up the login feature for the application.

#### Description of Task to be completed?

- Add tests for this login feature
- Consume the login endpoint.

#### How should this be manually tested?

Access the feature on `https://ah-bird-box-frontend-staging.herokuapp.com/login`

#### Any background context you want to provide?

A user should be able to login to their account if they already have an account and provide the correct login credentials for their account.

#### What are the relevant pivotal tracker stories?

[#163388212](https://www.pivotaltracker.com/story/show/163388212)

#### Screenshots (if appropriate):

![image](https://user-images.githubusercontent.com/5156758/54269190-f3881d80-458d-11e9-8903-4331def1bd4b.png)

#### Questions:

None

#### Reviewers:

@TooColline
@calebrotich10
@unah254
@bryan-munene
@hoslack

2019-03-13 20:25 UTC, TooColline commented on package.json
> +    "dotenv": "^6.2.0",
Hey, @bryan-munene I suggest you get rid of `dotenv` because we don't need it.

2019-03-15 06:24 UTC, calebrotich approved these changes
Apart from the inline styling in Login.jsx component, everything else is well done.

2019-03-15 06:28 UTC, TooColline commented on src/components/Navigation.jsx
> +  // isAuth() {
Hey @bryan-munene please remove the commented out code

2019-03-15 07:20 UTC, unah254 reviewed
Apart from the inline comments as mentioned by Collins, looks good to me

2019-03-15 09:27 UTC, hoslack requested changes

2019-03-15 09:27 UTC, hoslack commented on src/config/configAxios.js
> +axios.defaults.baseURL = 'https://ah-bird-box-staging.herokuapp.com/api';
Hide this in an ENV

2019-03-15 10:47 UTC, bryan-munene commented on src/config/configAxios.js
> +axios.defaults.baseURL = 'https://ah-bird-box-staging.herokuapp.com/api';
done

2019-03-15 10:51 UTC, hoslack approved these changes

2019-03-15 10:51 UTC, merged