#163388204 Setup test environment
andela/ah-bird-box-frontend pull request #3
Opened 2019-03-05 12:00 UTC by calebrotich10

#### What does this PR do?
Sets up an environment for writing tests in the application

#### Description of the Tasks completed?
- Add enzyme
- Add jest
- Add setupTest.js to integrate enzyme with react and jest

#### How should this be manually tested?
- `npm install` to add dependencies
- At the terminal run `npm run test`
- Type `a` to run all tests

#### What are the relevant pivotal tracker stories?
[#163388204](https://www.pivotaltracker.com/story/show/163388204)

2019-03-05 14:17 UTC, hoslack approved these changes

2019-03-05 14:18 UTC, hoslack requested changes
Please solve the merge conflicts before I merge you PR

2019-03-06 06:05 UTC, TooColline reviewed
This works as expected . Great job in setting up jest and enzyme.

2019-03-06 10:18 UTC, bryan-munene approved these changes
LGTM

2019-03-07 08:06 UTC, closed without merging